apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  # RBAC policy definitions in CSV format
  policy.csv: |
    # Developers can get applications in 'frontend-team'
    p, role:developer, applications, get, frontend-team/*, allow
    # Developers can sync applications in 'frontend-team'
    p, role:developer, applications, sync, frontend-team/*, allow 
    p, role:developer, applications, get, demo-project/*, allow
    p, role:developer, applications, sync, demo-project/*, allow
    p, role:developer, applications, update, demo-project/*, allow
    # Admins can perform any action on any application
    p, role:admin, applications, *, *, allow
    # Assign 'developer' role to user 'alice'
    g, alice, role:developer 
    # Assign 'admin' role to user 'bob'
    g, bob, role:admin 
  # Default role for users not explicitly assigned
  policy.default: role:readonly
